Repository xtray85/space-station-14, pull requests merged in 2023-07, with the labels that each got.

#179 some fixes and added quadro
  Resources/Maps/quadro.yml
  Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json
  Resources/Textures/Objects/Misc/bureaucracy.rsi/paper_stamp-cent.png
Labels: Changes: Sprites, Changes: Map, No C#

#180 fix quadro
  Resources/Maps/quadro.yml
Labels: Changes: Map, No C#

#181 added plushie
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_jessie.png
Labels: Changes: Sprites, Changes: Localization, No C#

#184 Update Rules
  Resources/ServerInfo/Rules.txt
Labels: No C#

#183 Замена оружия Синего Щита (нерф)
  Resources/Locale/ru-RU/ADT/Catalog/fills/items/belt.ftl
  Resources/Prototypes/ADT/KD/Cargo/VectorCrate.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: Changes: Localization, No C#

#191 Добавлена телескопическая дубинка(Done.)
  Content.Server/ADT/SwitchableWeapon/SwitchableWeaponSystem.cs
  Content.Shared/ADT/SwitchableWeapon/SwitchableWeaponComponent.cs
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/AstraKnife.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/melee.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/swichableweapon.ftl
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/off-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/off-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/on-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/on-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/telescope_off.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/telescope_on.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/off-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/off-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/on-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/on-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/telescope_off.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_bob.rsi/telescope_on.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/off-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/off-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/on-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/on-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/telescope_off.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton_kon.rsi/telescope_on.png
Labels: Changes: Sprites, Changes: Localization

#194 Мелкие фиксы.
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/swichableweapon.ftl
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Labels: Changes: Localization, No C#
