Repository xtray85/space-station-14, pull requests merged in 2023-04, with the labels that each got.

#65 Fix time for srtarting professions
  Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Labels: No C#

#64 Hairs3103
  Resources/Locale/ru-RU/ADT/Vulpkanin/hairs.ftl
  Resources/Prototypes/ADT/Customization/Markings/hair.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Customization/Markings/Vulpkanin_hair.yml
  Resources/Textures/ADT/Customization/Markings/hair.rsi/ayanami.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/buble_gum.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/mavis.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#63 Описание к профессиям
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Prototypes/ADT/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/ADT/Roles/Jobs/Medical/virusolog.yml
Labels: Changes: Localization, No C#

#67 added few wedding suits
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_ghotic_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_ghotic_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_ghotic_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_ghotic_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_ghotic_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_luna.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_luna.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_luna.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_luna.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_luna.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_rose_wedding_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_rose_wedding_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_rose_wedding_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_rose_wedding_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_rose_wedding_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_white_wedding_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_white_wedding_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_white_wedding_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_white_wedding_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/lush_white_wedding_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_ghotic_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_ghotic_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_ghotic_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_ghotic_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_ghotic_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_short_wedding_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_short_wedding_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_short_wedding_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_short_wedding_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_short_wedding_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_wedding_suit_luna.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_wedding_suit_luna.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_wedding_suit_luna.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_wedding_suit_luna.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_wedding_suit_luna.rsi/meta.json
Labels: Changes: Sprites, No C#

#69 +Fix
  Resources/Prototypes/ADT/Drones/Foodbot/Entities/Mobs/Player/servicedrone.yml
Labels: No C#

#72 Добавляет галоши в автомат уборщика
  Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
Labels: No C#

#70 Kirra set
  Resources/Prototypes/ADT/Entities/Clothing/Head/kirava-hoodsec.yml
  Resources/Prototypes/ADT/Entities/Clothing/Neck/KirravaCloaks.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/KirravaCloak.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/whips.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/KiiravaSword.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/bouquets.yml
  Resources/Prototypes/ADT/Lixon/Kiirava_Magic_Wand.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/kirava_hoodsec.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/kirava_hoodsec.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/kirava_hoodsec.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kiras_cloakns.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kiras_cloakns.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kiras_cloakns.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/kiras_cloakn.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/kiras_cloakn.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/kiras_cloakn.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/whips.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Fun/whips.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/whips.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/whips.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/whips.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/kiiravamagicwand.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/kiiravamagicwand.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/kiiravamagicwand.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/kiiravamagicwand.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/black_bouquet.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/black_bouquet.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/black_bouquet.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/black_bouquet.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/bouquet_with_beer.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/bouquet_with_beer.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/bouquet_with_beer.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/bouquet_with_beer.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/kiirava-sword.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/kiirava-sword.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/kiirava-sword.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/kiirava-sword.rsi/meta.json
Labels: Changes: Sprites, No C#

#73 Добавил одежду Луны (пока что без луномата)
  Resources/Locale/ru-RU/ADT/Luna/WeddingContentDresses.ftl
  Resources/Locale/ru-RU/ADT/Luna/WeddingContentGloves.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Hands/RedLongGloves.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/tankdispenser.yml
  Resources/Textures/ADT/Clothing/Hands/Gloves/long-red-gloves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/long-red-gloves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/long-red-gloves.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_black_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_black_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_black_suit.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_white_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_white_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/airy_white_suit.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black-elegant-dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black-elegant-dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black-elegant-dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black-elegant-dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black-elegant-dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange-beach-suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange-beach-suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange-beach-suit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange-beach-suit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange-beach-suit.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/red_cocktail_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/red_cocktail_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/red_cocktail_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/red_cocktail_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/red_cocktail_dress.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#74 Added whip
  Resources/Audio/Effects/whip.ogg
  Resources/Prototypes/ADT/Entities/Objects/Fun/whips.yml
  Resources/Textures/ADT/Objects/Fun/ERP/flogger.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/ERP/flogger.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/ERP/flogger.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/ERP/flogger.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/ERP/whips.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Fun/ERP/whips.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/ERP/whips.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/ERP/whips.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/ERP/whips.rsi/meta.json
Labels: Changes: Sprites, No C#

#75 Added four new shuttles
  Resources/Maps/ADT/Shuttles/Helios_chariot.yml
  Resources/Maps/ADT/Shuttles/Jastreb_Spirit_Of_The_Steppe.yml
  Resources/Maps/ADT/Shuttles/LSS36Mk2.yml
  Resources/Maps/ADT/Shuttles/Silver_chariot.yml
Labels: No C#

#76 S hark tail
  Resources/Locale/ru-RU/ADT/Markings/markings.ftl
  Resources/Maps/Dungeon/Ganki0Katorga_.yml
  Resources/Prototypes/ADT/Customization/Markings/shark.yml
  Resources/Textures/ADT/Mobs/Customization/shark_parts.rsi/meta.json
  Resources/Textures/ADT/Mobs/Customization/shark_parts.rsi/shark_fin.png
  Resources/Textures/ADT/Mobs/Customization/shark_parts.rsi/shark_tail.png
  Resources/Textures/Mobs/Species/Reptilian/parts.rsi/head_f.png
  Resources/Textures/Mobs/Species/Reptilian/parts.rsi/torso_f.png
Labels: Changes: Sprites, Changes: Localization, No C#

#79 Prepare to huds add
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
Labels: No C#

#81 Part One. Primary mechanicals from Sirena for huds.
  Content.Client/Sirena/EntityHealthBar/EntityHealthBarOverlay.cs
  Content.Client/Sirena/EntityHealthBar/ShowHealthBarsSystem.cs
  Content.Client/Sirena/EntityJobInfo/EntityJobInfoOverlay.cs
  Content.Client/Sirena/EntityJobInfo/ShowJobInfoSystem.cs
  Content.Shared/Sirena/Clothing/ClothingGrantComponentComponent.cs
  Content.Shared/Sirena/Clothing/ClothingGrantTagComponent.cs
  Content.Shared/Sirena/Clothing/ClothingGrantingSystem.cs
  Content.Shared/Sirena/EntityHealthBar/ShowHealthBarsComponent.cs
  Content.Shared/Sirena/EntityJobInfo/ShowJobInfoComponent.cs
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
  Resources/Textures/Interface/Misc/health_state.rsi/critical_state.png
  Resources/Textures/Interface/Misc/health_state.rsi/dead_state.png
  Resources/Textures/Interface/Misc/health_state.rsi/life_state.png
  Resources/Textures/Interface/Misc/health_state.rsi/meta.json
  Resources/Textures/Interface/Misc/health_status.rsi/background.png
  Resources/Textures/Interface/Misc/health_status.rsi/meta.json
Labels: Changes: Sprites

#82 +animation
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/meta.json
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_dtiger.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_dtiger_behind.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_dtiger_front.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_ltiger.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_ltiger_behind.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_ltiger_front.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_smooth.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_smooth_behind.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_smooth_front.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_spikes.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_spikes_behind.png
  Resources/Textures/Mobs/Customization/reptilian_parts.rsi/tail_spikes_front.png
Labels: Changes: Sprites, No C#

#83 Але, на проводе
  Resources/Prototypes/Catalog/Research/technologies.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/caseless_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/heavy_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/light_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/pistol.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
Labels: No C#

#80 ADT brig medic prepare to delete. Fix blueshield role for few maps
  Resources/Locale/en-US/job/job-names.ftl
  Resources/Locale/ru-RU/ADT/KD/BrigMedic/BrigMedic.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Prototypes/ADT/Roles/Jobs/BrigMedic/BrigMedic.yml
  Resources/Prototypes/ADT/Roles/Jobs/BrigMedic/BrigMedicHeadset.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueSheld/OfficerBlueSheld.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueSheld/backpack.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/barratry.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/kettle.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/moose.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/origin.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Roles/play_time_trackers.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/BrigMedic.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: Changes: Sprites, Changes: Map, Changes: Localization, No C#

#86 Modify SpecOpsNinjaSuit
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/MogesSpecOps.yml
Labels: Changes: Localization, No C#

#87 Исправлен BoxSurvivalSecurity у HOS
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
Labels: No C#

#88 Add tranq45
  Resources/Locale/ru-RU/ADT/Projectilles/magnum.ftl
  Resources/Locale/ru-RU/ADT/Reagents/adt_medicine.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Boxes/ammunition.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magnum.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/magnum.yml
  Resources/Prototypes/ADT/Reagents/toxins.yml
  Resources/Prototypes/ADT/Recipes/Reactions/chemicals.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/nano_scale_armor_chameleon_head.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Boxes/magnum.rsi/hvt.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Boxes/magnum.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_smg_mag.rsi/high_velocity_tranqvilizer.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_smg_mag.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#89 Выдаем СЩ скафандр
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hardsuit-helmets.ftl
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueSheld/backpack.yml
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Objects/Specific/Security/BlueShieldBox.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Recipes/Lathes/medical.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
Labels: Changes: Localization, No C#

#90 fix 1 symbol ''c'' >> "c"
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_spike.rsi/meta.json
Labels: No C#

#91 Чиним, да
  Resources/Locale/en-US/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/specific/security/BlueShieldBox.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/security/BlueShieldBox.ftl
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Objects/Specific/Security/BlueShieldBox.yml
Labels: Changes: Localization, No C#

#92 Опять доделываю то, что сделал не правильно
  Resources/Prototypes/Catalog/Research/technologies.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: No C#

#94 AddSpecialWhip
  Resources/Locale/ru-RU/ADT/Fun/pillow.ftl
  Resources/Locale/ru-RU/ADT/Fun/whips.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/whips.yml
  Resources/Textures/ADT/Clothing/Neck/Chokers/choker_heart.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_spike.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_spike.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_spike.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/ERP/escu_whip.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Fun/ERP/escu_whip.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/ERP/escu_whip.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/ERP/escu_whip.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/ERP/escu_whip.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/ERP/ritas_whip.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Fun/ERP/ritas_whip.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/ERP/ritas_whip.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/ERP/ritas_whip.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/ERP/ritas_whip.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#95 Изменение спрайта кошко-мальчика
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Customization/Markings/Tajaran.yml
  Resources/Textures/Mobs/Customization/tajaran_head.rsi/meta.json
  Resources/Textures/Mobs/Customization/tajaran_head.rsi/muzzle.png
  Resources/Textures/Mobs/Customization/tajaran_head.rsi/muzzleinears.png
  Resources/Textures/Mobs/Customization/tajaran_head.rsi/nose.png
  Resources/Textures/Mobs/Customization/tajaran_head.rsi/tiger_face.png
  Resources/Textures/Mobs/Customization/tajaran_tail.rsi/meta.json
  Resources/Textures/Mobs/Customization/tajaran_tail.rsi/tail_tip.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/head_f.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/head_m.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/meta.json
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/overlay_husk.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/tajaran_m.png
Labels: Changes: Sprites, No C#

#99 Added one more hardsiut for events
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTFunsuits.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/misc.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Cybersun.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/CybersunBodyguard.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/FunOuterClothing.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersun_crysis_head.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersun_crysis_head.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersun_crysis_head.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersun_crysis_head.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersun_crysis_head.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Misc/racoonhead.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Misc/racoonhead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Misc/racoonhead.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersun_crysis_hardsuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersun_crysis_hardsuit.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersun_crysis_hardsuit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersun_crysis_hardsuit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersun_crysis_hardsuit.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/racoon.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/racoon.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/racoon.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/garbagerama-inhand-left.png
  Resources/Textures/Objects/Fun/toys.rsi/garbagerama-inhand-right.png
  Resources/Textures/Objects/Fun/toys.rsi/garbagerama.png
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#97 Fixed some textures
  Resources/Prototypes/ADT/Entities/Clothing/Neck/Chokers.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/reptilian.yml
  Resources/Textures/ADT/Clothing/Neck/Chokers/choker_with_heart.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/choker_with_heart.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/choker_with_heart.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_with_spike.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_with_spike.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_with_spike.rsi/meta.json
Labels: Changes: Sprites, No C#

#102 Shark
  Resources/Prototypes/Entities/Mobs/Customization/Markings/shark.yml
Labels: No C#

#103 Kobolt
  Resources/Locale/ru-RU/markings/kobalt.ftl
  Resources/Locale/ru-RU/species/species.ftl
  Resources/Prototypes/Body/Organs/kobalt.yml
  Resources/Prototypes/Body/Parts/kobalt.yml
  Resources/Prototypes/Body/Prototypes/kobalt.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/kobalt.yml
  Resources/Prototypes/Entities/Mobs/Player/kobalt.yml
  Resources/Prototypes/Entities/Mobs/Species/kobalt.yml
  Resources/Prototypes/Species/kobalt.yml
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/meta.json
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/tail_m.png
Labels: Changes: Sprites, Changes: Localization, No C#

#104 Слова для всех
  Resources/Locale/ru-RU/accent/accents.ftl
  Resources/Locale/ru-RU/accent/dwarf.ftl
  Resources/Locale/ru-RU/accent/mobster.ftl
  Resources/Locale/ru-RU/accent/pirate.ftl
  Resources/Prototypes/Accents/word_replacements.yml
Labels: Changes: Localization, No C#

#105 HotFix
  Resources/Locale/ru-RU/species/species.ftl
  Resources/Prototypes/Entities/Mobs/Species/kobalt.yml
Labels: Changes: Localization, No C#

#106 Toys
  Resources/Prototypes/ADT/Entities/Objects/Fun/buttplug.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/dildo.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/vibrator.yml
  Resources/Prototypes/tags.yml
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/green_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/green_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/green_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/metal_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/metal_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/metal_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/pink_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/pink_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/pink_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/tail_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/tail_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/tail_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/teal_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/teal_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/teal_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/yellow_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/yellow_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/buttplug.rsi/yellow_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_avian.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_canine.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_double.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_dragon.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_equine.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_human.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/dildo_tentacle.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/polydildo_big.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/polydildo_med.png
  Resources/Textures/ADT/Objects/Fun/ERP/dildo.rsi/polydildo_small.png
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/magicwand_hard.png
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/vibrator_green.png
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/vibrator_pink.png
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/vibrator_red.png
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/vibrator_teal.png
  Resources/Textures/ADT/Objects/Fun/ERP/vibrator.rsi/vibrator_yellow.png
  Resources/Textures/Corvax/Mobs/Customization/cat_parts.rsi/meta.json
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/tail_m.png
Labels: Changes: Sprites, No C#

#108 Supersoldier's rig armor changed
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Cybersun.yml
Labels: No C#

#109 +suitsynd
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/fem_syndie.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndiecommanderhead_fem.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndiecommanderhead_fem.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndiecommanderhead_fem.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndiecommanderhead_fem.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndiecommanderhead_fem.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndieelitehead_fem.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndieelitehead_fem.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndieelitehead_fem.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndieelitehead_fem.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndieelitehead_fem.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndihead_fem.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndihead_fem.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndihead_fem.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndihead_fem.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/syndihead_fem.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndi_fem.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndi_fem.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndi_fem.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndi_fem.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndi_fem.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndiecommander_fem.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndiecommander_fem.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndiecommander_fem.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndiecommander_fem.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndiecommander_fem.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndieelite_fem.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndieelite_fem.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndieelite_fem.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndieelite_fem.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/syndieelite_fem.rsi/meta.json
Labels: Changes: Sprites, No C#

#110 Configure armor after event prepare
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Cybersun.yml
Labels: No C#
