Repository xtray85/space-station-14, pull requests merged in 2023-05, with the labels that each got.

#111 Demon
  Resources/Locale/ru-RU/species/species.ftl
  Resources/Prototypes/ADT/Demon/Body/Organs/demon.yml
  Resources/Prototypes/ADT/Demon/Body/Parts/demon.yml
  Resources/Prototypes/ADT/Demon/Body/Prototypes/demon.yml
  Resources/Prototypes/ADT/Demon/Customization/Markings/demon.yml
  Resources/Prototypes/ADT/Demon/Mobs/Player/demon.yml
  Resources/Prototypes/ADT/Demon/Mobs/Species/demon.yml
  Resources/Prototypes/ADT/Demon/Species/demon.yml
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/cow_ears.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/cow_horns.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/cow_spots.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/deer_antlers_horns.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/demon_tail.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/guards_stripes.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/lines_emperos.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/long.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/meta.json
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/queen_lines.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/small_horns.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/tree_lines.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/trinity_spots.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/up.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/full_f.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/full_m.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/full_t.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/head_f.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/head_m.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/head_t.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/l_arm.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/l_foot.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/l_hand.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/l_leg.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/meta.json
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/r_arm.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/r_foot.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/r_hand.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/r_leg.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/tail.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/torso_f.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/torso_m.png
  Resources/Textures/ADT/Mobs/Demon/parts.rsi/torso_t.png
Labels: Changes: Sprites, Changes: Localization, No C#

#112 Фикс канала Ботов
  Resources/Prototypes/ADT/Drones/Drone-Engineer/Entities/Mobs/Player/engineeringdrone.yml
  Resources/Prototypes/ADT/Drones/Drone-Medical/Entities/Mobs/Player/medicaldrone.yml
  Resources/Prototypes/ADT/Drones/Drone-Service/Entities/Mobs/Player/servicedrone.yml
  Resources/Prototypes/ADT/Drones/Foodbot/Entities/Mobs/Player/servicedrone.yml
  Resources/Prototypes/ADT/KD/Channels/Channels/RoboticChannel.yml
  Resources/Prototypes/ADT/KD/Channels/keys/RoboticKey.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Structures/Machines/telecomms.yml
Labels: No C#

#113 Fix demon
  Resources/Prototypes/ADT/Demon/Customization/Markings/demon.yml
  Resources/Prototypes/ADT/Demon/Species/demon.yml
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/demon_ears.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/goatee.png
  Resources/Textures/ADT/Mobs/Demon/custom.rsi/meta.json
Labels: Changes: Sprites, No C#

#115 Fixed mover for custom races
  Resources/Prototypes/ADT/Demon/Body/Parts/demon.yml
  Resources/Prototypes/ADT/Moth/Body/Parts/moth.yml
  Resources/Prototypes/ADT/Shark/Body/Parts/Shark.yml
  Resources/Prototypes/ADT/Tajaran/Body/Parts/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Body/Parts/Vulpkanin.yml
  Resources/Prototypes/Body/Parts/kobalt.yml
Labels: No C#

#114 Kobolt
  Resources/Maps/Misc/corvax_terminal.yml
  Resources/Prototypes/Body/Organs/kobalt.yml
  Resources/Prototypes/Entities/Mobs/Species/kobalt.yml
Labels: No C#

#116 Спрайты
  Resources/Prototypes/ADT/Shark/Species/Shark.yml
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/hos_hardsuithead.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/hos_hardsuithead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/hos_hardsuithead.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/hos_hardsuithead.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/hos_hardsuithead.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/warden_hardsuithead.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/warden_hardsuithead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/warden_hardsuithead.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/warden_hardsuithead.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/warden_hardsuithead.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/hos_hardsuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/hos_hardsuit.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/hos_hardsuit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/hos_hardsuit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/hos_hardsuit.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/warden_hardsuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/warden_hardsuit.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/warden_hardsuit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/warden_hardsuit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/warden_hardsuit.rsi/meta.json
  Resources/Textures/Clothing/Ears/Headsets/base.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/cargo.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/centcom.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/command.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/engineering.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/medical.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/medicalscience.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/mining.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/robotics.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/science.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/security.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/service.rsi/equipped-EARS.png
  Resources/Textures/Clothing/Ears/Headsets/servicesecurity.rsi/equipped-EARS.png
Labels: Changes: Sprites, No C#

#117 +ninesuit
  Resources/Prototypes/ADT/Entities/Objects/Fun/nine.yml
  Resources/Prototypes/Maps/origin.yml
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/bmf.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/bmf.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/bmf.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/border.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/border.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/border.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/kvdhead.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/kvdhead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/kvdhead.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/millitary.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/millitary.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/millitary.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/msh.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/msh.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/msh.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/musical.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/musical.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/musical.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/mvd.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/mvd.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/mvd.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/sea.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/sea.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/Nine/sea.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/bmf.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/bmf.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/bmf.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/border.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/border.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/border.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/commonnine.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/commonnine.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/commonnine.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/kvd.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/kvd.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/kvd.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/millitary.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/millitary.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/millitary.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/musical.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/musical.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/musical.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Nine/sea.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/sea.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Nine/sea.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Armor/bulletproof.rsi/meta.json
  Resources/Textures/Objects/Storage/boxes.rsi/meta.json
Labels: Changes: Sprites, Changes: Map, No C#

#118 Задача по автозамене
  Content.Server/Chat/Managers/ChatSanitizationManager.cs
  Content.Server/Corvax/ChatFilter/ChatSystem.cs
  Resources/Locale/ru-RU/chat/sanitizer-replacements.ftl
Labels: Changes: Localization

#123 -вырезаем гнанатомет
  Resources/Prototypes/Catalog/uplink_catalog.yml
Labels: No C#

#124 Added ump
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#125 Cнова фиксим цену. Абузят даже так
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/caseless_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/heavy_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/light_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/pistol.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
Labels: No C#

#126 Добавлен скафандр
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/cerber.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cerber_helmet.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cerber_helmet.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cerber_helmet.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cerber_helmet.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cerber_helmet.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cerber.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cerber.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cerber.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cerber.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cerber.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#127 Перевел названия — парамедик, офицер синего щита
  Resources/Locale/en-US/job/job-names.ftl
  Resources/Locale/ru-RU/administration/commands/polymorph-command.ftl
  Resources/Locale/ru-RU/administration/commands/throw-scoreboard-command.ftl
  Resources/Locale/ru-RU/explosions/explosion-resistance.ftl
  Resources/Locale/ru-RU/ghost/ghost-gui.ftl
  Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/prototypes/access/accesses.ftl
  Resources/ServerInfo/Guidebook/Science/Xenoarchaeology.xml
  Resources/ServerInfo/Guidebook/Security/DNA.xml
Labels: Changes: Localization, No C#

#128 Добавлена локализация Магистрата
  Resources/Locale/ru-RU/job/job-names.ftl
Labels: Changes: Localization, No C#

#130 Jaws of life comeback
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Labels: No C#

#132 CBURN agent powerup
  Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
Labels: No C#

#134 Fix taser
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Labels: No C#

#135 Updated Narsi content
  Resources/Locale/ru-RU/ADT/Narsi/narsi.ftl
  Resources/Prototypes/ADT/Drones/nar_si.yml
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/blody_eyes.png
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/blody_eyes_dead.png
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/bunch_demonic_eyes.png
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/bunch_demonic_eyes_dead.png
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/demonic_eye.png
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/demonic_eye_dead.png
  Resources/Textures/ADT/Mobs/Aliens/nar_si_demons.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#136 change torso and head lizard female
  Resources/Textures/Mobs/Species/Reptilian/parts.rsi/head_f.png
  Resources/Textures/Mobs/Species/Reptilian/parts.rsi/torso_f.png
Labels: Changes: Sprites, No C#

#138 fix музыки и замена тазера.
  Resources/Audio/Announcements/war.ogg
  Resources/Audio/Misc/epsilon.ogg
  Resources/Prototypes/ADT/KD/Entites/Storage/RingStorage.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueSheld/backpack.yml
  Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml
Labels: No C#

#139 Усложняем легкие крафты крутых item
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Recipes/Lathes/devices.yml
  Resources/Prototypes/Recipes/Lathes/medical.yml
Labels: No C#

#141 Fix
  Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
  Resources/ServerInfo/Rules.txt
Labels: No C#

#142 added flavor info (test)
  Content.Client/FlavorText/FlavorText.xaml
  Content.Client/FlavorText/FlavorText.xaml.cs
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
  Resources/Locale/ru-RU/ADT/Interface/interface.ftl
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
Labels: Changes: UI, Changes: Localization

#143 Fix
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/research/technologies.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/moose.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Recipes/Lathes/medical.yml
  Resources/Prototypes/Research/biochemical.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/ADTBlueShieldOfficer.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: Changes: Sprites, Changes: Map, Changes: Localization

#144 maps
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Eyes/hud.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/pda/pda-component.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/barratry.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
  Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
  Resources/Textures/ADT/Clothing/Eyes/HUD/captain.rsi/equipped-EYES.png
  Resources/Textures/ADT/Clothing/Eyes/HUD/captain.rsi/icon.png
  Resources/Textures/ADT/Clothing/Eyes/HUD/captain.rsi/meta.json
  Resources/Textures/Clothing/Eyes/Hud/sec.rsi/equipped-EYES.png
Labels: Changes: Sprites, Changes: Map, Changes: Localization, No C#

#145 Fix
  Content.Server/Anomaly/AnomalySystem.Generator.cs
  Content.Server/Anomaly/Components/AnomalyGeneratorComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Entities/Mobs/Player/human.yml
  Resources/Prototypes/Research/experimental.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/CustomId.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: Changes: Sprites

#146 Fix
  Resources/Changelog/ChangelogADT.yml
  Resources/Maps/Salvage/asteroid-base.yml
  Resources/Maps/Salvage/cargo-1.yml
  Resources/Maps/Salvage/medium-1.yml
  Resources/Maps/Salvage/medium-crashed-shuttle.yml
  Resources/Maps/Salvage/medium-dock.yml
  Resources/Maps/Salvage/medium-library.yml
  Resources/Maps/Salvage/medium-pet-hospital.yml
  Resources/Maps/Salvage/medium-pirate.yml
  Resources/Maps/Salvage/medium-ruined-emergency-shuttle.yml
  Resources/Maps/Salvage/medium-silent-orchestra.yml
  Resources/Maps/Salvage/medium-template.yml
  Resources/Maps/Salvage/medium-vault-1.yml
  Resources/Maps/Salvage/ruin-cargo-salvage.yml
  Resources/Maps/Salvage/small-1.yml
  Resources/Maps/Salvage/small-2.yml
  Resources/Maps/Salvage/small-3.yml
  Resources/Maps/Salvage/small-4.yml
  Resources/Maps/Salvage/small-a-1.yml
  Resources/Maps/Salvage/small-ai-survey-drone.yml
  Resources/Maps/Salvage/small-ship-1.yml
  Resources/Maps/Salvage/small-template.yml
  Resources/Maps/Salvage/stationstation.yml
  Resources/Maps/Salvage/tick-colony.yml
  Resources/Maps/Salvage/wh-salvage.yml
Labels: No C#, Status: Needs Review
