Repository xtray85/space-station-14, pull requests merged in 2023-03, with the labels that each got.

#13 Paramedical starting gears
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/orientalears.yml
  Resources/Prototypes/ADT/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Textures/ADT/Clothing/Head/Hats/orientalears.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/orientalears.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/orientalears.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hats/orientalears.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hats/orientalears.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#15 Добавлнение старт гирта пилота СБ
  Resources/Locale/ru-RU/ADT/Lixon/Lixonitems.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/service/vending_machine_restock.ftl
  Resources/Prototypes/ADT/Lixon/PilotSB.yml
Labels: Changes: Localization, No C#

#16 Фикс гиров ОБР
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_Medic.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_Security.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_leader.yml
Labels: No C#

#17 Суккубус теперь Tail, Рога теперь HeadTop
  Resources/Prototypes/ADT/Customization/Markings/head.yml
  Resources/Prototypes/ADT/Customization/Markings/tale.yml
Labels: No C#

#18 Added hardsuit for event "Someone else's war"
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/CybersunBodyguard.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/off-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/off-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/cybersunbodyguard.rsi/on-inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersunbodyguard.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersunbodyguard.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersunbodyguard.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersunbodyguard.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/cybersunbodyguard.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#19 loadout fixed
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/orientalears.yml
Labels: No C#

#20 Фикс снаряги пилота и изменение описания
  Resources/Locale/ru-RU/ADT/Lixon/SoapHonk.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Prototypes/ADT/Lixon/PilotSB.yml
  Resources/Prototypes/ADT/Lixon/soap/soap.yml
Labels: Changes: Localization, No C#

#22 Добавил золотой тайзер!
  Resources/Prototypes/ADT/KD/gold-staner/gold-staner.yml
  Resources/Textures/ADT/Memes/gold-staner.rsi/base.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/equipped-BELT.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-left-0.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-left-1.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-left-2.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-left-3.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-left-4.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-right-0.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-right-1.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-right-2.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-right-3.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/inhand-right-4.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/mag-unshaded-0.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/mag-unshaded-1.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/mag-unshaded-2.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/mag-unshaded-3.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/mag-unshaded-4.png
  Resources/Textures/ADT/Memes/gold-staner.rsi/meta.json
Labels: Changes: Sprites, No C#

#23 Страшные звуки для ивентов. Прописываются только в ручную
  Resources/Audio/hallucinations/behind_you1.ogg
  Resources/Audio/hallucinations/behind_you2.ogg
  Resources/Audio/hallucinations/far_noise.ogg
  Resources/Audio/hallucinations/growl1.ogg
  Resources/Audio/hallucinations/growl2.ogg
  Resources/Audio/hallucinations/growl3.ogg
  Resources/Audio/hallucinations/i_see_you1.ogg
  Resources/Audio/hallucinations/i_see_you2.ogg
  Resources/Audio/hallucinations/im_here1.ogg
  Resources/Audio/hallucinations/im_here2.ogg
  Resources/Audio/hallucinations/look_up1.ogg
  Resources/Audio/hallucinations/look_up2.ogg
  Resources/Audio/hallucinations/over_here1.ogg
  Resources/Audio/hallucinations/over_here2.ogg
  Resources/Audio/hallucinations/over_here3.ogg
  Resources/Audio/hallucinations/turn_around1.ogg
  Resources/Audio/hallucinations/turn_around2.ogg
  Resources/Audio/hallucinations/veryfar_noise.ogg
  Resources/Audio/hallucinations/wail.ogg
Labels: No C#

#25 + к Карго
  Resources/Locale/ru-RU/ADT/KD/CrateSMG.ftl
  Resources/Prototypes/ADT/KD/Cargo/GravityForCargo.yml
  Resources/Prototypes/ADT/KD/Cargo/VectorCrate.yml
  Resources/Prototypes/ADT/KD/Crates/VectorCrate.yml
Labels: Changes: Localization, No C#

#27 Добавил табак в автомат с сигами
  Resources/Prototypes/Catalog/VendingMachines/Inventories/cigs.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
Labels: No C#

#29 Добавил новый канал "роботический"
  Resources/Prototypes/ADT/Drones/Drone-Engineer/Entities/Mobs/Player/engineeringdrone.yml
  Resources/Prototypes/ADT/Drones/Drone-Medical/Entities/Mobs/Player/medicaldrone.yml
  Resources/Prototypes/ADT/Drones/Drone-Service/Entities/Mobs/Player/servicedrone.yml
  Resources/Prototypes/ADT/KD/Channels/RoboticChannel.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Labels: No C#

#30 Фикс для бриг медика
  Resources/Locale/ru-RU/ADT/KD/BrigMedic.ftl
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/ADT/Roles/Jobs/BrigMedic/BrigMedic.yml
Labels: Changes: Localization, No C#

#35 Ручка творца
  Resources/Locale/ru-RU/ADT/KD/Magistrat/Magistrat.ftl
  Resources/Locale/ru-RU/ADT/KD/Pen/pen.ftl
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/ADT/KD/Entites/pen/pen.yml
  Resources/Prototypes/ADT/Lixon/Magistrate/Headset_Magistrate.yml
  Resources/Prototypes/ADT/Lixon/Magistrate/Magistrate.yml
  Resources/Prototypes/ADT/Lixon/Magistrate/PDAMagistrate.yml
  Resources/Prototypes/ADT/Lixon/Magistrate/playTimeTracker.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Headset_Magistrate.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/barratry.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/kettle.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/moose.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/origin.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Roles/play_time_trackers.yml
  Resources/Textures/ADT/KD/pen.rsi/meta.json
  Resources/Textures/ADT/KD/pen.rsi/pen.png
  Resources/Textures/Interface/Misc/job_icons.rsi/Magistrat.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: Changes: Sprites, Changes: Map, Changes: Localization, No C#

#50 Lizard properties
  Content.Server/ADT/Lizard/LizardBloodComponent.cs
  Content.Server/ADT/Lizard/LizardBloodSystem.cs
  Resources/Locale/ru-RU/ADT/Reagents/adt_medicine.ftl
  Resources/Prototypes/ADT/Reagents/medicine.yml
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
Labels: Changes: Localization

#42 Иконка ассистента.
  Content.Server/Capibara/CapibaraComponent.cs
  Content.Server/Capibara/CapibaraSystem.cs
  Resources/Locale/ru-RU/ADT/Animals/capibara/capibara.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/JanaHypo.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/AstraKnife.ftl
  Resources/Prototypes/ADT/Entities/Mobs/Capibara/Capibara.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/Hyppo.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/AstraKnife.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
  Resources/Prototypes/ADT/Roles/Jobs/Sponsor/Sponsor.yml
  Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/Entities/Mobs/Player/familiars.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Textures/ADT/Interface/Actions/capibaraborn.png
  Resources/Textures/ADT/Mobs/Capibara.rsi/capibara.png
  Resources/Textures/ADT/Mobs/Capibara.rsi/capibara_dead.png
  Resources/Textures/ADT/Mobs/Capibara.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/Hyppo.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Misc/Hyppo.rsi/hypo.png
  Resources/Textures/ADT/Objects/Misc/Hyppo.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Misc/Hyppo.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Misc/Hyppo.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/astra-knife.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Weapons/Melee/astra-knife.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/astra-knife.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/astra-knife.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/astra-knife.rsi/meta.json
  Resources/Textures/Interface/Misc/job_icons.rsi/Passenger.png
Labels: Changes: Sprites, Changes: Localization

#54 Cleanbot modify: Changed sprite, added body.
  Resources/Prototypes/ADT/Drones/Cleanbot modify/cleanbot.yml
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
  Resources/Textures/ADT/Mobs/Silicon/Bots/cleanbot.rsi/cleanbot.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/cleanbot.rsi/meta.json
Labels: Changes: Sprites, No C#

#56 Fixed some bugs
  Resources/Prototypes/ADT/KD/Channels/keys/RoboticKey.yml
  Resources/Prototypes/Corvax/Entities/Objects/Devices/encryption_keys.yml
  Resources/Textures/ADT/Clothing/Head/Hats/blueshield_beret.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/supreme-commander-armor.rsi/Описание для панциря главнокомандующего.txt
  Resources/Textures/ADT/Customization/Markings/hair.rsi/meta.json
  Resources/Textures/Clothing/Head/Helmets/light_riot.rsi/meta.json
  Resources/Textures/Mobs/Customization/moth_parts.rsi/meta.json
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/meta.json
  Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json
  Resources/Textures/Structures/Machines/VendingMachines/pillow-vending-machine.rsi/deny-unshaded.png
  Resources/Textures/Structures/Machines/VendingMachines/pillow-vending-machine.rsi/meta.json
Labels: Changes: Sprites, No C#

#61 Added new lobbyscreen
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/LobbyScreens/clown.png
  Resources/Textures/LobbyScreens/clown.png.yml
Labels: No C#

#59 Wedding suits part
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/wedding_hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/SupremeComanderJumpskirt.yml
  Resources/Textures/ADT/Clothing/Head/Hats/priest_weddind_hat.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/priest_weddind_hat.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/priest_weddind_hat.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hats/priest_weddind_hat.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hats/priest_weddind_hat.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_male.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_male.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_male.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_male.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_wedding_suit_male.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/blue_wedding_suit_male.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/blue_wedding_suit_male.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/blue_wedding_suit_male.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/blue_wedding_suit_male.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/blue_wedding_suit_male.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/brown_wedding_suit_male.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/brown_wedding_suit_male.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/brown_wedding_suit_male.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/brown_wedding_suit_male.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/brown_wedding_suit_male.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/priest_primal_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/priest_primal_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/priest_primal_suit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/priest_primal_suit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/priest_primal_suit.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/supreme-commander-uniform.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/supreme-commander-uniform.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/supreme-commander-uniform.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/supreme-commander-uniform.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/supreme-commander-uniform.rsi/meta.json
  Resources/Textures/Mobs/Customization/moth_parts.rsi/moth_antenna.png
  Resources/Textures/Mobs/Customization/moth_parts.rsi/moth_markings.png
  Resources/Textures/Mobs/Customization/moth_parts.rsi/moth_wings.png
Labels: Changes: Sprites, Changes: Localization, No C#

#57 deleted invalid png from moth/customization
  Resources/Textures/Mobs/Customization/moth_parts.rsi/moth_antenna.png
  Resources/Textures/Mobs/Customization/moth_parts.rsi/moth_markings.png
  Resources/Textures/Mobs/Customization/moth_parts.rsi/moth_wings.png
Labels: Changes: Sprites, No C#

#58 +fun+fix+Tunbaton
  Resources/Locale/ru-RU/ADT/Fun/pillow.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/security.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/pillows.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/jaystunbaton.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/PillowVendingMachine.yml
  Resources/Textures/ADT/Objects/Fun/daki.rsi/junal.png
  Resources/Textures/ADT/Objects/Fun/daki.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#60 Fixed time requirements for cadet/intern/RND assistant/technical assi…
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Labels: No C#
