Repository xtray85/space-station-14, pull requests merged in 2023-09, with the labels that each got.

#267 Emit emote system
  Content.Client/ADT/TailAnimantionSystem.cs
  Content.Server/ADT/EmitEmote/EmitEmoteSystem.cs
  Content.Shared/ADT/EmitEmote/BaseEmitEmoteComponent.cs
  Content.Shared/ADT/EmitEmote/EmitEmoteOnUseComponent.cs
  Resources/Locale/ru-RU/ADT/Objects/Fan/athletics.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/athletics.yml
  Resources/Prototypes/Voice/speech_emotes.yml
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/dumbbell10kg.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/dumbbell15kg.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/dumbbell20kg.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/dumbbell2kg.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/dumbbell5kg.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/dumbbell8kg.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/dumbbell.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/icon10.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/icon15.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/icon20.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/icon25.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/icon30.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/icon5.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/kettlebell.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization

#266 Новые шторы.
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ADT/Objects/structuries/decoration/curtains.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Structures/Decorations/curtains.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_darina.png
  Resources/Textures/ADT/Structures/Decoration/curtains.rsi/closed.png
  Resources/Textures/ADT/Structures/Decoration/curtains.rsi/meta.json
  Resources/Textures/ADT/Structures/Decoration/curtains.rsi/open.png
Labels: Changes: Sprites, Changes: Localization, No C#

#268 grammar check
  Resources/ServerInfo/ADT/NewCocktails.xml
Labels: No C#

#269 Мелкие изменения от 2 сентября
  Resources/Locale/ru-RU/ADT/Fills/cargo.ftl
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Maps/gammaarmory.yml
  Resources/Maps/infiltrator.yml
  Resources/Maps/infiltrator_old.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/Catalog/Cargo/cargo_cargo.yml
  Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
  Resources/Prototypes/Catalog/Cargo/cargo_security.yml
  Resources/Prototypes/Catalog/Fills/Crates/engineering.yml
  Resources/Prototypes/Catalog/Fills/Crates/security.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Corvax/Datasets/Names/corvax_death_commando.yml
Labels: Changes: Map, Changes: Localization, No C#

#270 Доп водолазки без рукавов, фикс переводов и id.
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/turtleneck.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/turtleneck.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_black_womensleeveless.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_black_womensleeveless.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_black_womensleeveless.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_blacksleeveless.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_blacksleeveless.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_blacksleeveless.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_white_womensleeveless.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_white_womensleeveless.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_white_womensleeveless.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_whiteblacksleeveless.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_whiteblacksleeveless.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_whiteblacksleeveless.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_whitesleeveless.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_whitesleeveless.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Turleneck/turleneck_whitesleeveless.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#271 Добавление шарфа в образовательных целях.
  Resources/Locale/ru-RU/ADT/Clothing/Neck/scarf.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Neck/scarfs.yml
  Resources/Textures/ADT/Clothing/Neck/windyscarf.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/windyscarf.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/windyscarf.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Neck/windyscarf.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Neck/windyscarf.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#272 небольшие бафы
  Content.Shared/Salvage/Fulton/FultonComponent.cs
  Content.Shared/Salvage/Fulton/FultonedComponent.cs
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/xc67.yml
  Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
  Resources/Prototypes/Catalog/Fills/Crates/armory.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/collector.yml
Labels: Changes: Localization

#276 Починил хитбоксы ксено (кроме руни), а так же перевёл крашеры
  Resources/Locale/ru-RU/ADT/crushers/crushers.ftl
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
  Resources/Textures/Mobs/Aliens/Xenos/rouny.rsi/running.png
  Resources/Textures/Mobs/Aliens/Xenos/runner.rsi/running.png
Labels: Changes: Sprites, Changes: Localization, No C#

#275 вернул револьвер детективу
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
Labels: No C#

#277 Пачка переводов, в основном для заказов карго
  Resources/Locale/ru-RU/ADT/cargo/bounties.ftl
  Resources/Locale/ru-RU/ADT/cargo/cargo-bounty-console.ftl
  Resources/Locale/ru-RU/ADT/robotics/mmi.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/spear.ftl
Labels: Changes: Localization, No C#

#279 Фикс спрайтов чокеров
  Resources/Textures/ADT/Clothing/Neck/Chokers/choker_with_heart.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Chokers/choker_with_spike.rsi/equipped-NECK.png
Labels: Changes: Sprites, No C#

#282 фикс нюкеров
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/smes.ftl
  Resources/Maps/infiltrator.yml
  Resources/Maps/infiltrator_old.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/dartgun.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/dartgun.yml
  Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Recipes/Lathes/chemistry.yml
  Resources/Prototypes/Research/biochemical.yml
  Resources/Textures/ADT/Structures/Power/smes.rsi/meta.json
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-oc0.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-oc1.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-oc2.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-og1.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-og2.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-og3.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-og4.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-og5.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-op0.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-op1.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-op2.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes-open.png
  Resources/Textures/ADT/Structures/Power/smes.rsi/smes.png
Labels: Changes: Sprites, Changes: Map, Changes: Localization, No C#

#281 всякий stuff.
  Resources/Locale/en-US/interaction/interaction-popup-component.ftl
  Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
  Resources/Locale/ru-RU/reagents/meta/consumable/drink/alcohol.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_bottles.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/iron_tray.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/skewer.yml
Labels: Changes: Localization, No C#

#283 ревёрт планеты нюкеров
  Resources/Maps/nukieplanet.yml
Labels: Changes: Map, No C#

#284 Диван и загрузочные экраны
  Resources/Locale/ru-RU/ADT/Objects/structuries/furniture/furniture.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/iron_tray.yml
  Resources/Prototypes/ADT/Entities/Structures/Furniture/deckchair.yml
  Resources/Prototypes/ADT/Entities/Structures/Furniture/sofa.yml
  Resources/Prototypes/ADT/Recipes/Construction/furniture.yml
  Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
  Resources/Prototypes/Recipes/Construction/Graphs/furniture/seats.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/ADT/Structures/Furniture/black_sofa.rsi/meta.json
  Resources/Textures/ADT/Structures/Furniture/black_sofa.rsi/sofa_left.png
  Resources/Textures/ADT/Structures/Furniture/black_sofa.rsi/sofa_middle.png
  Resources/Textures/ADT/Structures/Furniture/black_sofa.rsi/sofa_right.png
  Resources/Textures/ADT/Structures/Furniture/deckchair.rsi/deckchair.png
  Resources/Textures/ADT/Structures/Furniture/deckchair.rsi/meta.json
  Resources/Textures/LobbyScreens/Lunalita.png
  Resources/Textures/LobbyScreens/Lunalita.png.yml
  Resources/Textures/LobbyScreens/RobusTyanka.png
  Resources/Textures/LobbyScreens/RobusTyanka.png.yml
Labels: Changes: Sprites, Changes: Localization, No C#

#286 tea update
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cups.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/cup_and_teapot.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/dinnerware.yml
Labels: Changes: Localization, No C#

#287 Несколько малюсеньких исправлений переводов
  Content.Shared/Chat/ChatChannelExtensions.cs
  Content.Shared/Chat/ChatSelectChannel.cs
  Resources/Locale/ru-RU/ADT/Clothing/Back/Backpack.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Hands/gloves.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Head/beret.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Neck/cloak.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Underwear/clothingmuns.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/turtleneck.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTFunsuits.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Locale/ru-RU/ADT/Fun/dungeon_master.ftl
  Resources/Locale/ru-RU/ADT/KD/Clothing/Rings.ftl
  Resources/Locale/ru-RU/ADT/borgs/borgs.ftl
  Resources/Locale/ru-RU/ADT/cargo/cargo-bounty-console.ftl
Labels: Changes: Localization

#288 Фикс энергооружия нюкеров
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Labels: Changes: Localization, No C#

#289 убрал у нюкеров возможность покупать пингвинов
  Resources/Prototypes/Catalog/uplink_catalog.yml
Labels: No C#

#291 speech-emotes для athletics добавлены.
  Resources/Prototypes/ADT/Voice/speech_emotes.yml
Labels: No C#

#292 фиксы после апстрима корвакса
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/corvax/job/job-names.ftl
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/catalog/fills/backpacks/startergear/duffelbag.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
  Resources/Maps/at_quadro.yml
  Resources/Prototypes/ADT/Catalog/Fills/Items/pyotr_briefcase.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Datasets/Names/adt_nukeagent_names.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Magazines/rifle_ext.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/xc67.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
  Resources/Prototypes/Corvax/Maps/avrite.yml
  Resources/Prototypes/Corvax/Maps/delta.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
  Resources/Prototypes/Entities/Mobs/Player/human.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Maps/quadro.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
  Resources/Prototypes/tags.yml
Labels: Changes: Map, Changes: Localization, No C#

#295 фикс рецепта охранного техфаба
  Resources/Prototypes/Recipes/Lathes/security.yml
Labels: No C#

#296 исправление ямлинтера
  Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
Labels: No C#

#302 вещи к свадьбе Урога и Юны, и замена тайлов стекла
  Resources/Locale/ru-RU/ADT/Clothing/Hands/gloves.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Locale/ru-RU/ADT/Clothing/outerclothing.ftl
  Resources/Locale/ru-RU/ADT/Fills/djah_ring_box.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Items/djah_rings_storage.yml
  Resources/Prototypes/ADT/Entities/Clothing/Hands/djah_rings.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/pyotr_coat.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Prototypes/Tiles/floors.yml
  Resources/Textures/ADT/Clothing/Hands/ring_urog.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/ring_urog.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/ring_urog.rsi/meta.json
  Resources/Textures/ADT/Clothing/Hands/ring_yuna.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/ring_yuna.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/ring_yuna.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/oktyabrina_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/oktyabrina_coat.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/oktyabrina_coat.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/oktyabrina_coat.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/oktyabrina_coat.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/pyotr_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/yuna_black_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/yuna_black_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/yuna_black_dress.rsi/meta.json
  Resources/Textures/ADT/Structures/Furniture/leather_sofa.rsi/sofa_middle.png
  Resources/Textures/ADT/Structures/Furniture/violet_sofa.rsi/sofa_left.png
  Resources/Textures/ADT/Structures/Furniture/violet_sofa.rsi/sofa_middle.png
  Resources/Textures/ADT/Structures/Furniture/violet_sofa.rsi/sofa_right.png
  Resources/Textures/Tiles/glass.png
  Resources/Textures/Tiles/glass_alt.png
  Resources/Textures/Tiles/rglass.png
  Resources/Textures/Tiles/rglass_alt.png
Labels: Changes: Sprites, Changes: Localization, No C#

#301 кпк модуль боргов
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/robotics.yml
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/icon-pda.png
  Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/meta.json
Labels: Changes: Sprites, No C#

#305 пальмы!
  Resources/Locale/ru-RU/ADT/Objects/Decoration/palm_tree.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/ammunition/boxes/srifle.ftl
  Resources/Prototypes/ADT/Entities/Objects/Decoration/palmtree.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Textures/ADT/Objects/Decoration/palm_tree.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/palm_tree.rsi/palm1.png
  Resources/Textures/ADT/Objects/Decoration/palm_tree.rsi/palm2.png
Labels: Changes: Sprites, Changes: Localization, No C#

#304 Новые законы у двух боргов
  Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml
Labels: No C#

#306 Транквилизатор больше не имба
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
Labels: No C#

#307 Скажем нет роботтсерам
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Labels: No C#

#311 Я запрещаю автоматам говорить
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
Labels: No C#

#312 Быстрые правки
  Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
  Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRoleEntryButtons.xaml
  Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRoleRulesWindow.xaml
  Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesEntry.xaml.cs
  Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesEui.cs
  Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesWindow.xaml
  Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesWindow.xaml.cs
  Content.Server/Corvax/ChatFilter/ChatSystem.cs
  Content.Server/Ghost/Roles/Components/GhostRoleComponent.cs
  Content.Shared/Ghost/Roles/GhostRolesEuiMessages.cs
  Content.Shared/Roles/AntagPrototype.cs
  Content.Shared/Roles/JobRequirements.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/preferences/ui/humanoid-profile-editor.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/ammuniton/speedloader357.ftl
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/muchhurt.yml
  Resources/Prototypes/Catalog/Cargo/cargo_food.yml
  Resources/Prototypes/Catalog/Fills/Crates/food.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chefvend.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/antimateriel.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Roles/Antags/ninja.yml
  Resources/Prototypes/Roles/Antags/nukeops.yml
Labels: Changes: UI, Changes: Localization

#313 бафф ОБР
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/muchhurt.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_Medic.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_Security.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_leader.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/icon-on.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/on-equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/magboots-ert.rsi/on-inhand-right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#314 Мелкие фиксы.
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Tajaran/Species/Tajaran.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_akula.png
Labels: Changes: Sprites, Changes: Localization, No C#

#317 Emergency light3
  Resources/Audio/ADT/Ambience/Objects/warning-buzzer-alarm-fascinatedsound.ogg
  Resources/Prototypes/ADT/Entities/Objects/Power/base_lightning.yml
  Resources/Prototypes/ADT/Entities/Objects/Power/lights.yml
  Resources/Textures/ADT/Structures/Wallmounts/Lighting/emergency_light.rsi/base.png
  Resources/Textures/ADT/Structures/Wallmounts/Lighting/emergency_light.rsi/meta.json
  Resources/Textures/ADT/Structures/Wallmounts/Lighting/emergency_light.rsi/off.png
  Resources/Textures/ADT/Structures/Wallmounts/Lighting/emergency_light.rsi/on.png
Labels: Changes: Sprites, No C#

#319 фикс здоровья щитов
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
Labels: No C#

#320 кто то пропустил день ног
  Resources/Prototypes/ADT/Demon/Body/Parts/demon.yml
  Resources/Prototypes/ADT/Shark/Body/Parts/Shark.yml
  Resources/Prototypes/ADT/Tajaran/Body/Parts/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Body/Parts/Vulpkanin.yml
  Resources/Prototypes/Body/Parts/diona.yml
  Resources/Prototypes/Body/Parts/kobalt.yml
Labels: No C#

#322 Foxtails
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Markings/foxtails.ftl
  Resources/Prototypes/ADT/Customization/Markings/foxtails.yml
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/meta.json
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_prime.png
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_second.png
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_third.png
Labels: Changes: Sprites, Changes: Localization, No C#

#323 Новые звуки для каракалов.
  Resources/Audio/ADT/carakal_hiss.ogg
  Resources/Audio/ADT/carakal_purr.ogg
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Labels: No C#, Status: Needs Review

#327 Таксиботы стали быстрее
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Labels: No C#

#328 Фикс нижнего белья и ребаланс аплинка
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Catalog/fills/items/xc67ammobundle.ftl
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/Species/moth.yml
  Resources/Textures/ADT/Clothing/Shoes/Boots/black_footwraps.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/meta.json
  Resources/Textures/ADT/Structures/Furniture/church_bench.rsi/bench_left.png
  Resources/Textures/ADT/Structures/Furniture/church_bench.rsi/bench_middle.png
  Resources/Textures/ADT/Structures/Furniture/church_bench.rsi/bench_right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#329 Уменьшение числа HUD`ов у СБ
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
  Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Labels: No C#

#331 paramedick access
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Labels: No C#

#333 Больше киборгов
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Labels: No C#

#334 Игрушка Празата
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/johan_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_breeches.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_breeches.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_shorts.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_shorts.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/johan_pants.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/johan_pants.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_breeches.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_breeches.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_shorts.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/white_shorts.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_prazat.png
Labels: Changes: Sprites, Changes: Localization, No C#
