Repository xtray85/space-station-14, pull requests merged in 2023-06, with the labels that each got.

#148 Added few things (without translate)
  Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/misc.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/FunOuterClothing.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/ADT/Entities/Structures/Piping/Atmospherics/miners.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/ADT/Clothing/Hands/Gloves/nova_gloves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/nova_gloves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/nova_gloves.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Misc/foxhead.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Misc/foxhead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Misc/foxhead.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/fox.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/fox.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/fox.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_elegant_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_elegant_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_elegant_dress.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_elegant_dress.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/black_elegant_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/druid_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/druid_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/druid_dress.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange_beach_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange_beach_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange_beach_suit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange_beach_suit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/orange_beach_suit.rsi/meta.json
  Resources/Textures/LobbyScreens/UnderTheTree.png
  Resources/Textures/LobbyScreens/UnderTheTree.png.yml
Labels: Changes: Sprites, No C#

#151 Added few things
  Resources/Locale/ru-RU/ADT/Clothing/FormalKits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Prototypes/ADT/Entities/Loadout/loadouts.yml
  Resources/Textures/ADT/Clothing/Head/Hats/true_detective_hat.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/true_detective_hat.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/true_detective_hat.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hats/true_detective_hat.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hats/true_detective_hat.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/true_detective_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/true_detective_coat.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/true_detective_coat.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/true_detective_coat.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/true_detective_coat.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/true_detective_jumpskirt.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/true_detective_jumpskirt.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/true_detective_jumpskirt.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/true_detective_jumpskirt.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/true_detective_jumpskirt.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#154 Balance
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Body/Parts/silicon.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Objects/Misc/machine_parts.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml
  Resources/Prototypes/Entities/Objects/Specific/Research/anomaly.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
  Resources/Prototypes/Entities/Objects/Tools/jetpacks.yml
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Entities/Objects/Tools/welders.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
  Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/pipes.yml
  Resources/Textures/ADT/Clothing/Mask/raven.rsi/meta.json
Labels: No C#

#157 hotfix bug
  Resources/Prototypes/Catalog/uplink_catalog.yml
Labels: No C#

#156 Added few things and customizations
  Resources/Locale/ru-RU/ADT/Clothing/FormalKits.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Hands/gloves.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTFunsuits.ftl
  Resources/Prototypes/ADT/Customization/Markings/hair.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Textures/ADT/Clothing/Head/Hats/bat_hat.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/bat_hat.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/bat_hat.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/lilit_black_dress.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/lilit_black_dress.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/lilit_black_dress.rsi/meta.json
  Resources/Textures/ADT/Customization/Markings/hair.rsi/bubble_gum.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/buble_gum.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/cloud.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/meta.json
  Resources/Textures/ADT/Customization/Markings/hair.rsi/morning_hairstyle.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/morning_hairstyle_2.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/ponytail.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/prince_charming.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/shaved_female.png
  Resources/Textures/ADT/Customization/Markings/hair.rsi/shaved_unisex.png
Labels: Changes: Sprites, Changes: Localization, No C#

#159 translation fix
  Resources/Locale/ru-RU/ADT/Narsi/narsi.ftl
Labels: Changes: Localization, No C#

#160 added new tails for vulps
  Resources/Locale/ru-RU/ADT/Markings/vulpmarkings.ftl
  Resources/Prototypes/ADT/Body/Parts/stepan.yml
  Resources/Prototypes/ADT/Body/Prototypes/stepan.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Customization/Markings/Vulpkanin.yml
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/meta.json
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/tail1.png
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/tail2.png
  Resources/Textures/Mobs/Species/Vulpkanin/parts.rsi/meta.json
  Resources/Textures/Mobs/Species/Vulpkanin/parts.rsi/tail_m.png
Labels: Changes: Sprites, Changes: Localization, No C#

#163 Fix pallets
  Resources/Prototypes/Entities/Objects/Specific/Cargo/cargo_pallet.yml
  Resources/Textures/Clothing/Under/Socks/bee.rsi/equipped-SOCKS.png
  Resources/Textures/Clothing/Under/Socks/bee.rsi/meta.json
  Resources/Textures/Clothing/Under/Socks/coder.rsi/equipped-SOCKS.png
  Resources/Textures/Clothing/Under/Socks/coder.rsi/meta.json
Labels: Changes: Sprites, No C#

#162 Добавлена фуражка и костюм Dungeon Master'а
  Resources/Locale/ru-RU/ADT/Fun/dungeon_master.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Textures/ADT/Clothing/Head/Hats/dungeon_master.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/dungeon_master.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/dungeon_master.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/dungeon_master_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/dungeon_master_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/dungeon_master_suit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/dungeon_master_suit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/dungeon_master_suit.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#166 janitorFix
  Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
Labels: No C#, Status: Needs Review

#167 added new rig and weapon for event
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/AstraKnife.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/saibasain.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/Swords.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/saiba_sain_hardsuit_helmet.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/saiba_sain_hardsuit_helmet.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/saiba_sain_hardsuit_helmet.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/saiba_sain_hardsuit_helmet.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/saiba_sain_hardsuit_helmet.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/saiba_sain_hardsuit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/saiba_sain_hardsuit.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/saiba_sain_hardsuit.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/saiba_sain_hardsuit.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/saiba_sain_hardsuit.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/murasama.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/murasama.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/murasama.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/murasama.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#, Status: Needs Review

#168 vulp tails fix
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/tail1.png
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/tail2.png
  Resources/Textures/Mobs/Species/Vulpkanin/parts.rsi/tail_m.png
Labels: Changes: Sprites, No C#, Status: Needs Review

#169 Добавлено поведение хвостов и некоторые анимации.
  Content.Client/ADT/TailAnimantionSystem.cs
  Content.Client/Content.Client - Ярлык.lnk
  Content.Client/Sirena/Animations/EmoteAnimationSystem.cs
  Content.Server/Sirena/Animations/EmoteAnimationSystem.cs
  Content.Shared/Chat/Prototypes/EmotePrototype.cs
  Content.Shared/Sirena/Animations/EmoteAnimationComponent.cs
  Content.Shared/Sirena/Animations/SharedEmoteAnimationSystem.cs
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Sirena/Actions/emotes.yml
Labels: Status: Needs Review

#171 airlocks fix. base_structureairlocks.yml corvax openUnlitVisible: true
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
Labels: No C#, Status: Needs Review
