Repository xtray85/space-station-14, pull requests merged in 2023-08, with the labels that each got.

#195 Hotfix
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Corvax/Entities/Objects/Misc/stamps.yml
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/l_foot.png
  Resources/Textures/Mobs/Species/Vulpkanin/parts.rsi/l_foot.png
Labels: Changes: Sprites, No C#

#196 Добавление базы для абакана. Пока что с текстурами от акмс.
  Resources/Prototypes/Entities/Objects/Weapons/Guns/AbakanRifle/burstFireRifles.yml
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/base.png
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/mag-0.png
  Resources/Textures/Objects/Weapons/Guns/BurstRifles/abakan.rsi/meta.json
Labels: Changes: Sprites, No C#

#198 добавлены кое-какие переводы
  Resources/Locale/en-US/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/prototypes/entities/clothing/Neck/scarfs.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/armor.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/misc.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/computer.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/healing.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/e_sword.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/computers.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/lathe.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/closets/base_structureclosets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/closets/lockers/lockers.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
Labels: Changes: Localization, No C#

#203 Новые вещи и фиксы.
  Resources/Audio/ADT/pereklyuchenie-verevochkoy.ogg
  Resources/Audio/ADT/schelchok-vyiklyucheniya.ogg
  Resources/Locale/ru-RU/ADT/Catalog/fills/items/encryption_keys.ftl
  Resources/Locale/ru-RU/ADT/Catalog/fills/items/headsets.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/knifess.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/swichableweapon.ftl
  Resources/Prototypes/ADT/Catalog/RadioChannels/MercChannel.yml
  Resources/Prototypes/ADT/Catalog/RadioChannels/SpecChannel.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/aidan.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/MercEncryptionKey.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/MercHeadset.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/SpecEncryptionKey.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/SpecHeadset.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/abakan.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/folding_knife.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
  Resources/Textures/ADT/Clothing/Ears/Headsets/armyheadset.rsi/equipped-EARS.png
  Resources/Textures/ADT/Clothing/Ears/Headsets/armyheadset.rsi/icon.png
  Resources/Textures/ADT/Clothing/Ears/Headsets/armyheadset.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/stormer_maugly.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/stormer_maugly.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/stormer_maugly.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/stormer_maugly.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/stormer_maugly.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/plushie_aidan.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/plushie_aidan.rsi/plushie_aidan.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/blade.png
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/off-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/off-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/on-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/folding_knife.rsi/on-inhand-right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#205 Какао и рецепт шоколада
  Resources/Locale/ru-RU/ADT/Flavors/flavor-profiles.ftl
  Resources/Locale/ru-RU/ADT/Hydroponics/cocoa_seed.ftl
  Resources/Locale/ru-RU/ADT/Hydroponics/cocoa_tree.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/cocoa_solid_pack.ftl
  Resources/Locale/ru-RU/ADT/Reagents/cocoa_solid.ftl
  Resources/Locale/ru-RU/ADT/Reagents/liquid_chocolate.ftl
  Resources/Locale/ru-RU/ADT/Reagents/liquid_cocoa.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/chocodrink_glass.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/cocoa_glass.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/cocoa_pod.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/cocoa_solid_pack.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Hydroponics/cocoa_seeds.yml
  Resources/Prototypes/ADT/Flavors/flavors.yml
  Resources/Prototypes/ADT/Hydroponics/cocoa_tree.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/liquid_chocolate.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/liquid_cocoa.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Food/cocoa_solid.yml
  Resources/Prototypes/ADT/Recipes/Cooking/choco_bar_recipe.yml
  Resources/Prototypes/ADT/Recipes/Cooking/choco_drink_recipe.yml
  Resources/Prototypes/ADT/Recipes/Reactions/cocoa_react.yml
  Resources/Prototypes/Catalog/Fills/Crates/botany.yml
  Resources/Prototypes/Catalog/Fills/Crates/food.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chefvend.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/seeds.yml
  Resources/Textures/ADT/Objects/Consumable/Drinks/cocoa_drink.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/cocoa_drink.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/cocoa_pack.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Food/cocoa_pack.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/dead.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/harvest.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/produce.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/seed.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/stage-1.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/stage-2.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/stage-3.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/stage-4.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/stage-5.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cocoa.rsi/stage-6.png
  SpaceStation14.sln
Labels: Changes: Sprites, Changes: Localization, No C#

#206 Мелкие фиксы переводов и армейский жетон.
  Resources/Locale/en-US/ss14-ru/prototypes/adt/kd/gold-staner/gold-staner.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Neck/cloak.ftl
  Resources/Locale/ru-RU/ADT/Clothing/clothingUSSP.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/kd/gold-staner/gold-staner.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Neck/armyjeton.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
  Resources/Textures/ADT/Clothing/Neck/armytoken.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/armytoken.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/armytoken.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#225 Переделка экипировки Синего Щита
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hardsuit-helmets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: Changes: Localization, No C#

#223 По настоящему возвращаю молнии
  Resources/Prototypes/Entities/Effects/lightning.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: No C#

#229 фикс пары ошибок и переводы
  Resources/Locale/ru-RU/weapons/ranged/gun.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/AbakanRifle/burstFireRifles.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/abakan.rsi/meta.json
  Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json
  Resources/Textures/Structures/Machines/microwave.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#224 Человеческие волосы у Вульп
  Resources/Locale/ru-RU/ADT/Vulpkanin/hairs.ftl
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Customization/Markings/Vulpkanin_hair.yml
Labels: Changes: Localization, No C#

#233 Фиксы
  Resources/Audio/Misc/license.txt
  Resources/Audio/Misc/tension_session.ogg
  Resources/Prototypes/ADT/Customization/Markings/augbody.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ppch_45u.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ppch_45u.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/SMGs/ump.rsi/meta.json
Labels: Changes: Sprites, No C#

#231 Ребаланс ксеносов
  Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
  Resources/Prototypes/ADT/Demon/Mobs/Species/demon.yml
  Resources/Prototypes/ADT/Shark/Entities/Mobs/Species/Shark.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Species/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Species/Vulpkanin.yml
  Resources/Prototypes/Damage/modifier_sets.yml
  Resources/Prototypes/Entities/Mobs/Species/kobalt.yml
Labels: No C#

#228 Обновление снаряжения Синего Щита
  Resources/Locale/ru-RU/ADT/Clothing/Back/Backpack.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Head/beret.ftl
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Armor/blueshield_armor.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Underwear/blueshield_underwear.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/roles/jobs/officerblueshield/backpack.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/blueshield_beret.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/blueshield_armor.yml
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/blueshield_underwear.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Textures/ADT/Clothing/Back/blueshield_backpack.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Clothing/Back/blueshield_backpack.rsi/icon.png
  Resources/Textures/ADT/Clothing/Back/blueshield_backpack.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Back/blueshield_backpack.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Belt/blueshield_webbing.rsi/equipped-BELT.png
  Resources/Textures/ADT/Clothing/Belt/blueshield_webbing.rsi/icon.png
  Resources/Textures/ADT/Clothing/Belt/blueshield_webbing.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Belt/blueshield_webbing.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Belt/blueshield_webbing.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/blueshield_armor.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/blueshield_armor.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/blueshield_armor.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/blueshield_armor.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_boxers.rsi/equipped-UNDERWEARB.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_boxers.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_boxers.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/blueshield_bra.rsi/equipped-UNDERWEART.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_bra.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_bra.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/blueshield_panties.rsi/equipped-UNDERWEARB.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_panties.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/blueshield_panties.rsi/meta.json
  Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#232 пак мелких изменений
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/Corvax/Objectives/goals.yml
  Resources/Prototypes/Entities/Objects/Specific/Chemistry/chem_bag.yml
  Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
  Resources/Prototypes/Entities/Objects/Specific/Salvage/ore_bag.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/antimateriel.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/special.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/window.yml
  Resources/Prototypes/Recipes/Construction/Graphs/utilities/fan.yml
  Resources/Prototypes/Recipes/Construction/structures.yml
  Resources/Prototypes/Recipes/Construction/utilities.yml
Labels: Changes: Localization, No C#

#230 добавил открытый болт для христова
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Customization/Markings/headaugs.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/snipers/new_hristov.yml
  Resources/Textures/ADT/Mobs/Customization/augments/headaugs.rsi/malstrem.png
  Resources/Textures/ADT/Objects/Weapons/Guns/new_hristov.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/new_hristov.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#235 Cargo time
  Content.Shared/Salvage/Expeditions/Modifiers/SalvageTimeMod.cs
  Resources/Locale/ru-RU/ADT/Clothing/alljaycloth.ftl
  Resources/Locale/ru-RU/ADT/Fills/lavalend.ftl
  Resources/Locale/ru-RU/ADT/Hydroponics/mutated_seed.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-engineering.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-security.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/engineering-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/security-crates.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/USSPjuggernaut.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/inquisitory.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/marinne.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Hydroponics/seeds/mutatedseeds.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Research/disk.yml
  Resources/Prototypes/ADT/Entities/Structures/Storage/Crates/crates.yml
  Resources/Prototypes/ADT/Fills/Crates/ADTrewards.yml
  Resources/Prototypes/ADT/Hydroponics/leaves/mutatedproduct.yml
  Resources/Prototypes/ADT/Hydroponics/seeds/mutated.yml
  Resources/Prototypes/Catalog/Bounties/bounties.yml
  Resources/Prototypes/Catalog/Cargo/cargo_engineering.yml
  Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
  Resources/Prototypes/Catalog/Cargo/cargo_security.yml
  Resources/Prototypes/Catalog/Fills/Crates/engineering.yml
  Resources/Prototypes/Catalog/Fills/Crates/security.yml
  Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
  Resources/Prototypes/Entities/Objects/Specific/Research/disk.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/techdiskterminal.yml
  Resources/Prototypes/Procedural/salvage_mods.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/off-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/off-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/inquisitoryhead.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/inquisitory.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/inquisitory.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/inquisitory.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/dead.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/harvest.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/produce.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/seed.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/stage-1.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/stage-2.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/cannabiswhite.rsi/stage-3.png
  Resources/Textures/ADT/Structures/Storage/Crates/lavalend.rsi/base.png
  Resources/Textures/ADT/Structures/Storage/Crates/lavalend.rsi/closed.png
  Resources/Textures/ADT/Structures/Storage/Crates/lavalend.rsi/meta.json
  Resources/Textures/ADT/Structures/Storage/Crates/lavalend.rsi/open.png
  Resources/Textures/Structures/Storage/closet.rsi/brigmedlocked.png
  Resources/Textures/Structures/Storage/closet.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, Status: Needs Review

#239 Сервисный апдейт
  Resources/Locale/ru-RU/ADT/Flavors/flavor-profiles.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/just_kekc_coctails_glass.ftl
  Resources/Locale/ru-RU/ADT/Reagents/just_kekc_cocktails.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/just_kekc_cocktails_glass.yml
  Resources/Prototypes/ADT/Flavors/flavors.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/just_kekc_cocktails.yml
  Resources/Prototypes/ADT/Recipes/Reactions/just_kekc_coctails_recipe.yml
  Resources/Textures/ADT/Clothing/Head/Hats/pyotr_cap.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Jackets/barjacket.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtarcticexplosion.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtarcticlatte.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtazureblue.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtbizconversation.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtcitrusbalance.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtdobryidrink.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adteclipsedeclispe.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtgrapelady.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adthungoverangel.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtmilkeclipse.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtpenetrationdrink.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtsaturdaybaron.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtspacebush.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtspecialteaoolong.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtsugarknight.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtsummershade.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtwintersun.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#242 Фикс рецепта одного из коктейлей
  Resources/Prototypes/ADT/Recipes/Reactions/just_kekc_coctails_recipe.yml
  Resources/ServerInfo/ADT/NewCocktails.xml
Labels: No C#

#243 мелкие изменения от 23.08
  Resources/Locale/ru-RU/ADT/Fills/cargo_armory.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/mindshield_implant.ftl
  Resources/Locale/ru-RU/ADT/Objects/specific/medstuff.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_armory.yml
  Resources/Prototypes/ADT/Catalog/Fills/Crates/armory.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/mindshield_implant.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/combathypo.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_Medic.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/XenoArch/Effects/normal_effects.yml
  Resources/Textures/ADT/Objects/Specific/Medical/adt_combathypo.rsi/icon.png
  Resources/Textures/ADT/Objects/Specific/Medical/adt_combathypo.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Specific/Medical/adt_combathypo.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Specific/Medical/adt_combathypo.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#248 Фикс укрепленных стен
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
Labels: No C#

#245 20 новых плюшевых игрушек админов.
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-security.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Catalog/Cargo/cargo_security.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_abigail.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_ayus.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_bob.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_evgeniy.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_fries.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_ilumi.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_jan.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_jason.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_kus.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_lilit.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_luke.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_lya.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_nova.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_peter.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_rebecca.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_schrodinger.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_terenty.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_uvarov.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_valtor.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_walter.png
Labels: Changes: Sprites, Changes: Localization, No C#

#244 Бафф ИРП
  Resources/Prototypes/Catalog/Cargo/cargo_food.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
Labels: No C#

#246 Яблочно-алкогольное DLC к ©Сервисному апдейту
  Resources/Locale/ru-RU/ADT/Flavors/flavor-profiles.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/drink_bottles.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/just_kekc_coctails_glass.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/vodka_antivirus.ftl
  Resources/Locale/ru-RU/ADT/Reagents/just_kekc_cocktails.ftl
  Resources/Locale/ru-RU/ADT/Reagents/vodka_antivirus.ftl
  Resources/Locale/ru-RU/ADT/guidebook/guides.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/drink_bottles.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/just_kekc_cocktails_glass.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/vodka_antivirus.yml
  Resources/Prototypes/ADT/Flavors/flavors.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/just_kekc_cocktails.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/vodka_antivirus.yml
  Resources/Prototypes/ADT/Recipes/Reactions/just_kekc_coctails_recipe.yml
  Resources/Prototypes/Catalog/ReagentDispensers/beverage.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/ServerInfo/ADT/NewCocktails.xml
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtappleliqueur.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtappleliqueurbottle.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtapplemartini.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/adtbacardiapple.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/just_kekc_cocktail.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/vodka_antivirusbottle.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/vodka_antivirusbottle.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/vodka_antivirusglass.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/vodka_antivirusglass.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/ice_pack.rsi/icon.png
  Resources/Textures/ADT/Objects/Specific/zookeperhealthanalyzer.rsi/icon.png
Labels: Changes: Sprites, Changes: Localization, No C#

#252 небольшой ребаланс телескопички
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
Labels: No C#

#251 перенёс крафты магазинов кота
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
Labels: No C#

#249 Мелкие фиксы и небольшая обнова.
  Resources/Locale/ru-RU/ADT/Clothing/Underwear/clothingmuns.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/nine.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Locale/ru-RU/ADT/Objects/tanks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/fun/nine.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/GorkaClothingset.yml
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/clothingmuns.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/abakan.yml
  Resources/Prototypes/ADT/Entities/Structures/Storage/Tanks/tanks.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/tools.yml
  Resources/Textures/ADT/Clothing/Underwear/muns_bra_blue.rsi/equipped-UNDERWEART.png
  Resources/Textures/ADT/Clothing/Underwear/muns_bra_blue.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/muns_bra_blue.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/muns_bra_red.rsi/equipped-UNDERWEART.png
  Resources/Textures/ADT/Clothing/Underwear/muns_bra_red.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/muns_bra_red.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/muns_panties_blue.rsi/equipped-UNDERWEARB.png
  Resources/Textures/ADT/Clothing/Underwear/muns_panties_blue.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/muns_panties_blue.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/muns_panties_red.rsi/equipped-UNDERWEARB.png
  Resources/Textures/ADT/Clothing/Underwear/muns_panties_red.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/muns_panties_red.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_iohan.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/an_97.rsi/meta.json
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/meta.json
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/watertank-2-1.png
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/watertank-2-2.png
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/watertank-2-3.png
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/watertank-2-4.png
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/watertank-2-5.png
  Resources/Textures/ADT/Structures/Storage/tanks.rsi/watertank-2.png
Labels: Changes: Sprites, Changes: Localization, No C#

#250 небольшой пак баланса и фиксов
  Resources/Locale/en-US/ss14-ru/prototypes/adt/entities/clothing/outerclothing/marinne.ftl
  Resources/Locale/ru-RU/ADT/Clothing/alljaycloth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/outerclothing/marinne.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/entities/clothing/outerclothing/coats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/USSPjuggernaut.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/marinne.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
  Resources/Prototypes/Catalog/Fills/Crates/security.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
  Resources/Prototypes/Corvax/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/Corvax/sponsor.yml
  Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/antimateriel.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
Labels: Changes: Localization, No C#

#247 Дресс-код для ©Сервисного апдейта
  Resources/Prototypes/ADT/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/ADT/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
Labels: No C#

#253 Мелкие дополнения и исправления к ©Дополнению Сервиса
  Resources/Locale/ru-RU/ADT/Flavors/flavor-profiles.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/ArmtFlask.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/cherry_exquisite_wine.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/drink_bottles.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/just_kekc_coctails_glass.ftl
  Resources/Locale/ru-RU/ADT/Reagents/cherry_exquisite_wine.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/ArmyFlask.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/cherry_exquisite_wine.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/drink_bottles.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/mixing_glass.yml
  Resources/Prototypes/ADT/Flavors/flavors.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/cherry_exquisite_wine.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/just_kekc_cocktails.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/vodka_antivirus.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
  Resources/Textures/ADT/Objects/Consumable/Drinks/cherryexquisitewinebottle.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/cherryexquisitewinebottle.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/cherryexquisitewineglass.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/cherryexquisitewineglass.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/mixing_glass.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/mixing_glass.rsi/mixing_glass-front.png
  Resources/Textures/ADT/Objects/Misc/mixing_glass.rsi/mixing_glass.png
Labels: Changes: Sprites, Changes: Localization, No C#

#255 Фикс маски спрайта и фикс целей смены
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Corvax/Objectives/goals.yml
  Resources/Textures/Mobs/Customization/masking_helpers.rsi/female_full.png
Labels: Changes: Sprites, Changes: Localization, No C#

#257 Мелкий фикс.
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/GorkaClothingset.yml
Labels: No C#

#260 роли предателей и ядерных оперативников требуют время
  Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs
  Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
  Content.Shared/Roles/AntagPrototype.cs
  Resources/Prototypes/Roles/Antags/nukeops.yml
  Resources/Prototypes/Roles/Antags/traitor.yml
Labels: Changes: UI

#261 Фиксы 31.08.2023
  Resources/Maps/Shuttles/emergency_delta.yml
  Resources/Prototypes/ADT/Catalog/Fills/Items/pyotr_briefcase.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/xc67.yml
  Resources/Prototypes/Catalog/Bounties/bounties.yml
  Resources/Prototypes/Catalog/Cargo/cargo_security.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: No C#

#263 небольшой балансный патч
  Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Structures/Power/chargers.yml
Labels: Changes: Localization

#264 telescopic dubina upate
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/off-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/off-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/on-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/on-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/telescope_off.png
  Resources/Textures/ADT/Objects/Weapons/Melee/telescopic_baton.rsi/telescope_on.png
Labels: Changes: Sprites, No C#

#265 микро-микро добавления для ©Сервисного Апдейта
  Resources/Locale/ru-RU/ADT/Objects/Misc/glass_jug.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/glass_jug.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/cherry_exquisite_wine.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/just_kekc_cocktails.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/vodka_antivirus.yml
  Resources/Prototypes/Catalog/Fills/Items/toolboxes.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/dinnerware.yml
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/fill1.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/fill2.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/fill3.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/fill4.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/fill5.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/fill6.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/icon-front.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/icon.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Misc/glass_jug.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#
